#  
stages:
  - release
  - deploy

upload-helm-release:
  stage: release
  image: sharuman/debiank8s:latest  
  before_script:    
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG" >> ~/.kube/config
#       - cat /builds/std-ext-001-022/momo-store.tmp/KUBECONFIG >> ~/.kube/config
    - chmod 644 ~/.kube/config     
  script:    
    - helm lint ./momo-store-chart
    - CHART_FILE=$(helm package --version $VERSION ./momo-store-chart | grep "Successfully packaged chart" | awk '{print $NF}')    
    - echo "Uploading ${CHART_FILE} to Nexus..."
    - >
       curl -v -u std-ext-001-022:QY52z4qs $NEXUS_HELM_REPO --upload-file ${CHART_FILE}
  after_script:
    - rm ~/.kube/config       
  only:
    changes:
      - momo-store-chart/**/*
deploy:
  stage: deploy
  image: sharuman/debiank8s:latest
  environment:
    name: production/k8s
  before_script:    
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG"
    - cat /builds/std-ext-001-022/momo-store.tmp/KUBECONFIG >> ~/.kube/config
    - chmod 644 ~/.kube/config
    - cd momo-store-chart/
    - kubectl get services 
    - kubectl apply -f vpa-crd.yaml
    - kubectl apply -f vpa.yaml
  
  script:
    - helm repo add nexus $NEXUS_HELM_REPO --username $NEXUS_REPO_USER --password $NEXUS_REPO_PASS
    - helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
    - helm repo add grafana https://grafana.github.io/helm-charts
    - helm repo update
    - helm install ingress-nginx ingress-nginx/ingress-nginx
    - kubectl apply -f https://github.com/jetstack/cert-manager/releases/download/v1.8.0/cert-manager.yaml 
    - >       
       helm upgrade --install momo-store --atomic --timeout 15m
       nexus/momo-store || true
    - >       
       helm upgrade --install momo-store --atomic --timeout 15m
       nexus/momo-store    
    - helm upgrade --atomic --install loki grafana/loki-stack
    - kubectl get services
    - echo "use external IP nginx ingress for A record of your site"    
  after_script:     
    - rm ~/.kube/config          
  