stages:
  - deploy

variables:
  KUBECONFIG_PATH: /root/.kube/config

deploy:
  stage: deploy
  image: sharuman/debiank8s:latest
  environment:
    name: production/k8s
  before_script:    
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - apt-get update && apt-get install -y jq
    - export PATH=$PATH:/root/yandex-cloud/bin
    - yc config set token $YC_TOK
    - yc config set cloud-id $YC_CLOUD_ID
    - yc config set folder-id $YC_FOLDER_ID
    - mkdir -p ~/.kube
    - chmod +x ./momo-store-chart/kubeconfig.sh
    - bash ./momo-store-chart/kubeconfig.sh    
    - chmod 644 ~/.kube/config

  script:
    - echo "KUBECONFIG content:"
    - cat ~/.kube/config
    - kubectl get nodes
