#    
stages:
  - deploy

deploy:
  stage: deploy
  image: sharuman/debiank8s:latest
  environment:
    name: production/kluster-k8s    
  before_script:    
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export YC_TOKEN=$YC_TOKEN
    - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - export PATH=$PATH:/root/yandex-cloud/bin
    - yc config set token $YC_TOK
    - yc config set cloud-id $YC_CLOUD_ID
    - yc config set folder-id $YC_FOLDER_ID

    
  script:
    - cd yandex-k8s-cluster/
    - terraform init
    - terraform apply -auto-approve || true
    - mkdir -p ~/.kube
    - yc managed-kubernetes cluster get-credentials sharuman-k8s-cluster --external --force
    - cat ~/.kube/config
    - chmod 644 ~/.kube/config
#    - echo "$KUBECONFIG"
#    - cat /builds/std-ext-001-022/momo-store.tmp/KUBECONFIG >> ~/.kube/config    
    - terraform apply -auto-approve
  only:
    changes:
      - yandex-k8s-cluster/**/*
