#    
stages:
  - deploy

deploy:
  stage: deploy
  image: sharuman/debiank8s:latest
  environment:
    name: production/kluster-k8s    
  before_script:    
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export YC_TOKEN=$YC_TOKEN
    
  script:
    - cd yandex-k8s-cluster/
    - terraform init
    - terraform apply -auto-approve || true
    - terraform apply -auto-approve || true
  only:
    changes:
      - yandex-k8s-cluster/**/*
