#   
stages:
  - deploy

deploy:
  stage: deploy
  image: sharuman/debiank8s:latest
  environment:
    name: production/kluster-k8s    
  before_script:    
    - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
    - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
    - export YC_TOKEN=$YC_TOKEN
    
  script:
    - cd yandex-k8s-cluster/
    - terraform init
    - terraform apply -auto-approve || true
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG"
    - cat /builds/std-ext-001-022/momo-store.tmp/KUBECONFIG >> ~/.kube/config
    - chmod 644 ~/.kube/config     
    - terraform apply -auto-approve
  only:
    changes:
      - yandex-k8s-cluster/**/*
  after_script:     
    - rm ~/.kube/config
